# Generated by Django 5.0 on 2024-01-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default=5465, verbose_name='Язык'),
            preserve_default=False,
        ),
    ]
