# Generated by Django 5.0 on 2024-01-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
    ]
