# Generated by Django 5.0 on 2024-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='time',
            field=models.CharField(choices=[('1:00-2:00', '1:00-2:00')], verbose_name='Время'),
        ),
    ]
