# Generated by Django 5.0 on 2024-01-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название cтиля категории на русском')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Название cтиля категории на узбекском')),
            ],
            options={
                'verbose_name': 'Стиль Категории Мебели',
                'verbose_name_plural': 'Стили Категорий Мебель',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название категории на русском')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Название категории на узбекском')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalog.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория Мебели',
                'verbose_name_plural': 'Категории Мебели',
            },
        ),
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=155, verbose_name='Название мебели на русском')),
                ('title_uz', models.CharField(max_length=155, verbose_name='Название мебели на узбекском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='furnitures/', verbose_name='Фото')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_uz', models.TextField(verbose_name='Описание на узбекском')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Catalog.categories', verbose_name='Категория')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='Catalog.styles', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебель',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='furnitures/', verbose_name='Фото')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Catalog.furnitures')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галлерея',
            },
        ),
    ]
