# Generated by Django 5.0 on 2023-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitures',
            name='price',
            field=models.FloatField(default=2323, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
