# Generated by Django 5.0 on 2024-02-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_alter_furnitures_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='without_style',
            field=models.BooleanField(default=True, verbose_name='Без стиля'),
            preserve_default=False,
        ),
    ]
