# Generated by Django 5.0 on 2024-02-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0005_remove_styles_category_categories_without_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Catalog.categories', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
