# Generated by Django 5.0 on 2024-06-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0006_styles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='furnitures',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='furnitures',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='furnitures',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='furnitures',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='styles',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='styles',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='categories',
            name='title',
            field=models.CharField(default=3, max_length=100, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furnitures',
            name='description',
            field=models.TextField(default=32, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furnitures',
            name='title',
            field=models.CharField(default=3242, max_length=155, verbose_name='Название мебели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='styles',
            name='title',
            field=models.CharField(default=534, max_length=100, verbose_name='Название cтиля категории'),
            preserve_default=False,
        ),
    ]
