# Generated by Django 5.0 on 2023-12-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_orders_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date_to',
        ),
    ]
