# Generated by Django 5.0 on 2023-12-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_remove_orders_date_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='material',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='size',
        ),
    ]
