# Generated by Django 5.0 on 2023-12-12 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, null=True, verbose_name='Размер')),
                ('material', models.CharField(blank=True, null=True, verbose_name='Материал')),
                ('color', models.CharField(blank=True, null=True, verbose_name='Цвет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Фото')),
                ('date_to', models.DateField(verbose_name='До даты')),
                ('status', models.CharField(verbose_name='Статус')),
                ('completed', models.BooleanField(verbose_name='Выполнен')),
                ('furniture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to='Catalog.furnitures', verbose_name='Мебель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
