# Generated by Django 5.0 on 2023-12-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, null=True, verbose_name='Размер')),
                ('material', models.CharField(blank=True, null=True, verbose_name='Материал')),
                ('color', models.CharField(verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='orders/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to='Catalog.furnitures', verbose_name='Мебель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
