FROM python:3.11.6

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1


WORKDIR /api

COPY requirements.txt /api/

RUN pip install -r requirements.txt

COPY . /api/

CMD python api/manage.py runserver 0.0.0.0:8000

